### ISSUE TITLE
unknown configuration key: "region"

### ISSUE THREAD

**Issue by xenexis** [profitbricks/packer-builder-profitbricks#4]
Hi all,

I"m trying to get this great plugin to work, and it works if the "region" key is not set up in the config.json file, however it fails if I try to set a specific region : 

`packer validate config.json
Template validation failed. Errors are shown below.

Errors validating build 'profitbricks'. 1 error(s) occurred:

* unknown configuration key: "region"`

The relevant part of config.json:
`      "region": "de/fra",`

Any hint on that ?
Thanks!

**Comment by xenexis** [comment]
Hi,

I just realised it works with "location" rather then using "region" configuration key.

**Comment by jasminSPC** [comment]
Sorry for the inconvenience. The README file was not up-to-date.
